// lib/mock-data.ts
import { User, Thread, FileAsset, Message } from '@/types/chat';

export const MOCK_USERS: User[] = [
  { id: 'user-me', name: 'You', role: 'Product Designer', avatarBg: 'bg-indigo-600' },
  { id: 'user-bob', name: 'Bob Smith', role: 'Frontend Lead', avatarBg: 'bg-emerald-600' },
  { id: 'user-alice', name: 'Alice Johnson', role: 'UI Lead', avatarBg: 'bg-amber-600' },
  { id: 'user-carol', name: 'Carol Danvers', role: 'VP Operations', avatarBg: 'bg-rose-600' },
  { id: 'user-dave', name: 'Dave Miller', role: 'External Contractor', avatarBg: 'bg-slate-600' },
];

export const MOCK_THREADS: Thread[] = [
  {
    id: 't1',
    name: 'Product Launch Sync',
    description: 'Weekly team coordination for the Q3 release, design signoffs, and launch checkpoints.',
    coverImage: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=800&q=80',
    type: 'group',
    isPinned: true,
    pinnedMessageId: 'm2',
    memberIds: ['user-me', 'user-bob', 'user-alice'],
    creatorId: 'user-me',
    createdAt: '2026-09-01T08:30:00.000Z',
    threadTags: ['urgent', 'to-review'],
    tagPermission: 'all',
    allowedTaggerIds: ['user-me', 'user-bob', 'user-alice'],
    tagDefs: [
      {
        id: 'tg-inspire',
        name: 'Inspiration',
        description: 'Design benchmarks, motion references, and interaction models',
        color: 'bg-violet-100 dark:bg-violet-950/70 text-violet-700 dark:text-violet-300 border-violet-200 dark:border-violet-800/80',
        isUnique: false,
        category: 'inspiration',
        icon: '💡',
        createdAt: '2026-09-01T09:00:00.000Z',
        lastUsedAt: '2026-09-22T14:20:00.000Z',
        usageCount: 4,
      },
      {
        id: 'tg-link',
        name: 'Reference Link',
        description: 'Key external specifications, Figma canvases, and benchmark URLs',
        color: 'bg-cyan-100 dark:bg-cyan-950/70 text-cyan-700 dark:text-cyan-300 border-cyan-200 dark:border-cyan-800/80',
        isUnique: false,
        category: 'resource',
        icon: '🔗',
        createdAt: '2026-09-02T11:15:00.000Z',
        lastUsedAt: '2026-09-21T18:45:00.000Z',
        usageCount: 2,
      },
      {
        id: 'tg-idea',
        name: 'Creative Pitch',
        description: 'Exploratory concepts, micro-copy variations, and visual hooks',
        color: 'bg-amber-100 dark:bg-amber-950/70 text-amber-700 dark:text-amber-300 border-amber-200 dark:border-amber-800/80',
        isUnique: false,
        category: 'inspiration',
        icon: '🎨',
        createdAt: '2026-09-03T10:00:00.000Z',
        lastUsedAt: '2026-09-20T16:10:00.000Z',
        usageCount: 3,
      },
      {
        id: 'tg1',
        name: 'Decision',
        description: 'Confirmed design or architecture decisions reached by the team',
        color: 'bg-blue-100 dark:bg-blue-950/70 text-blue-700 dark:text-blue-300 border-blue-200 dark:border-blue-800/80',
        isUnique: false,
        category: 'decision',
        icon: '🎯',
        createdAt: '2026-09-04T13:40:00.000Z',
        lastUsedAt: '2026-09-23T09:12:00.000Z',
        usageCount: 5,
      },
      {
        id: 'tg2',
        name: 'Final Approval',
        description: 'Single required signoff before shipping to production',
        color: 'bg-emerald-100 dark:bg-emerald-950/70 text-emerald-700 dark:text-emerald-300 border-emerald-200 dark:border-emerald-800/80',
        isUnique: true,
        category: 'decision',
        icon: '✅',
        createdAt: '2026-09-05T15:00:00.000Z',
        lastUsedAt: '2026-09-22T17:30:00.000Z',
        usageCount: 1,
      },
      {
        id: 'tg-action',
        name: 'Action Item',
        description: 'Immediate tasks, deliverables, and assigned follow-ups',
        color: 'bg-orange-100 dark:bg-orange-950/70 text-orange-700 dark:text-orange-300 border-orange-200 dark:border-orange-800/80',
        isUnique: false,
        category: 'action',
        icon: '⚡',
        createdAt: '2026-09-06T09:20:00.000Z',
        lastUsedAt: '2026-09-23T11:05:00.000Z',
        usageCount: 6,
      },
      {
        id: 'tg3',
        name: 'Blocker',
        description: 'Critical roadblocks halting immediate progress',
        color: 'bg-rose-100 dark:bg-rose-950/70 text-rose-700 dark:text-rose-300 border-rose-200 dark:border-rose-800/80',
        isUnique: false,
        category: 'action',
        icon: '⚠️',
        createdAt: '2026-09-07T14:10:00.000Z',
        lastUsedAt: '2026-09-18T10:00:00.000Z',
        usageCount: 1,
      },
    ],
  },
  {
    id: 't2',
    name: 'Alice Johnson',
    description: '1-on-1 design feedback, asset reviews, and weekly check-ins.',
    type: 'dm',
    isPinned: false,
    memberIds: ['user-me', 'user-alice'],
    creatorId: 'user-alice',
    createdAt: '2026-09-08T10:00:00.000Z',
    threadTags: ['to-review'],
    tagPermission: 'creator',
    allowedTaggerIds: ['user-alice'],
    tagDefs: [
      {
        id: 'tg4',
        name: 'To-Do',
        description: 'Action items pending completion',
        color: 'bg-amber-100 dark:bg-amber-950/70 text-amber-700 dark:text-amber-300 border-amber-200 dark:border-amber-800/80',
        isUnique: false,
        createdAt: '2026-09-08T10:30:00.000Z',
        lastUsedAt: '2026-09-22T13:40:00.000Z',
        usageCount: 3,
      },
      {
        id: 'tg5',
        name: 'Follow Up',
        description: 'Items requiring follow-up or status check-in',
        color: 'bg-purple-100 dark:bg-purple-950/70 text-purple-700 dark:text-purple-300 border-purple-200 dark:border-purple-800/80',
        isUnique: false,
        createdAt: '2026-09-09T14:00:00.000Z',
        lastUsedAt: '2026-09-20T11:15:00.000Z',
        usageCount: 2,
      },
    ],
  },
  {
    id: 't3',
    name: 'Executive Compensation & Board Review',
    description: 'Confidential executive channel for board approvals and compensation adjustments.',
    type: 'group',
    isPrivate: true,
    isPinned: false,
    memberIds: ['user-bob', 'user-carol'],
    creatorId: 'user-carol',
    createdAt: '2026-09-10T16:00:00.000Z',
    threadTags: ['urgent', 'confidential'],
    tagPermission: 'admins',
    allowedTaggerIds: ['user-carol', 'user-bob'],
    tagDefs: [
      {
        id: 'tg-sec1',
        name: 'Confidential',
        description: 'Restricted board-only materials',
        color: 'bg-rose-100 dark:bg-rose-950/70 text-rose-700 dark:text-rose-300 border-rose-200 dark:border-rose-800/80',
        isUnique: false,
        createdAt: '2026-09-10T16:30:00.000Z',
        lastUsedAt: '2026-09-21T09:00:00.000Z',
        usageCount: 2,
      },
    ],
  },
  {
    id: 't4',
    name: 'Bob & Carol DM',
    description: 'Private 1-on-1 direct message channel between Bob and Carol.',
    type: 'dm',
    isPrivate: true,
    isPinned: false,
    memberIds: ['user-bob', 'user-carol'],
    creatorId: 'user-bob',
    createdAt: '2026-09-12T11:00:00.000Z',
    threadTags: ['hr-pending'],
    tagPermission: 'all',
    allowedTaggerIds: ['user-bob', 'user-carol'],
    tagDefs: [],
  },
];

export const MOCK_FILES: FileAsset[] = [
  {
    id: 'f1',
    threadId: 't1',
    name: 'hero-banner-concept.jpg',
    url: 'https://picsum.photos/seed/designlaunch88/1200/800',
    type: 'image/jpeg',
    size: 2450000,
  },
  {
    id: 'f2',
    threadId: 't1',
    name: 'podcast-intro-mixdown.mp3',
    url: 'https://actions.google.com/sounds/v1/ambiences/outdoor_ambience.ogg',
    type: 'audio/mp3',
    size: 1850000,
    duration: 65,
  },
  {
    id: 'f3',
    threadId: 't1',
    name: 'product-launch-teaser.mp4',
    url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    type: 'video/mp4',
    size: 4200000,
    duration: 15,
  },
];

export const MOCK_MESSAGES: Message[] = [
  {
    id: 'm1',
    threadId: 't1',
    content: 'Are we still on track for the launch next week? Let us make sure @Alice Johnson signs off.',
    sender: 'other',
    senderName: 'Bob Smith',
    timestamp: '10:00 AM',
    tagIds: [],
  },
  {
    id: 'm2',
    threadId: 't1',
    content: 'Yes, but we need to review the hero image typography and button placement.',
    sender: 'me',
    senderName: 'You',
    timestamp: '10:05 AM',
    isPinned: true,
    tagIds: ['tg1'],
    replyParentId: 'm1',
    replyToName: 'Bob Smith',
    replySnippet: 'Are we still on track for the launch next week?',
  },
  {
    id: 'm3',
    threadId: 't1',
    content: 'The CTA button here could use higher contrast against the gradient background.',
    sender: 'other',
    senderName: 'Bob Smith',
    timestamp: '10:12 AM',
    tagIds: [],
    annotationFileId: 'f1',
    annotationPoint: { x: 64.5, y: 68.2, pinNumber: 1 },
  },
  {
    id: 'm4',
    threadId: 't1',
    content: 'Agreed! I will update the button color to emerald green for higher visibility.',
    sender: 'me',
    senderName: 'You',
    timestamp: '10:15 AM',
    isEdited: true,
    editedAt: '10:16 AM',
    editHistory: [
      {
        content: 'Agreed! I will update the button color to deep blue.',
        editedAt: '10:15 AM',
      },
    ],
    tagIds: ['tg1', 'tg2'],
    annotationFileId: 'f1',
    annotationParentId: 'm3',
    replyParentId: 'm3',
    annotationReplyToName: 'Bob Smith',
    replyToName: 'Bob Smith',
    annotationRootContent: 'The CTA button here could use higher contrast against the gradient background.',
    replySnippet: 'The CTA button here could use higher contrast against the gradient background.',
  },
  {
    id: 'm-aud-1',
    threadId: 't1',
    content: 'The backing synth swell is a bit loud at 00:14. Can we dip it by -3dB so the vocal narration cuts through?',
    sender: 'other',
    senderName: 'Bob Smith',
    timestamp: '10:16 AM',
    tagIds: [],
    annotationFileId: 'f2',
    annotationPoint: { x: 21.5, y: 50, pinNumber: 1, timestampSeconds: 14 },
  },
  {
    id: 'm-aud-2',
    threadId: 't1',
    content: 'Notched out 1kHz on the synth pad — vocal is much crisper now!',
    sender: 'me',
    senderName: 'You',
    timestamp: '10:17 AM',
    tagIds: ['tg1'],
    annotationFileId: 'f2',
    annotationParentId: 'm-aud-1',
    replyParentId: 'm-aud-1',
    annotationReplyToName: 'Bob Smith',
    replyToName: 'Bob Smith',
    annotationRootContent: 'The backing synth swell is a bit loud at 00:14. Can we dip it by -3dB so the vocal narration cuts through?',
    replySnippet: 'The backing synth swell is a bit loud at 00:14...',
  },
  {
    id: 'm-aud-3',
    threadId: 't1',
    content: 'Love this acoustic riser right before the drop at 00:42! Great pacing.',
    sender: 'other',
    senderName: 'Alice Johnson',
    timestamp: '10:17 AM',
    tagIds: ['tg-inspire'],
    annotationFileId: 'f2',
    annotationPoint: { x: 64.6, y: 50, pinNumber: 2, timestampSeconds: 42 },
  },
  {
    id: 'm-vid-1',
    threadId: 't1',
    content: 'The product title card at 00:06 should hold on screen for another second before fading.',
    sender: 'other',
    senderName: 'Alice Johnson',
    timestamp: '10:18 AM',
    tagIds: [],
    annotationFileId: 'f3',
    annotationPoint: { x: 40.0, y: 50, pinNumber: 1, timestampSeconds: 6 },
  },
  {
    id: 'm-poll-1',
    threadId: 't1',
    content: 'Team poll: When should we freeze code for the final Q3 release candidate?',
    sender: 'other',
    senderName: 'Bob Smith',
    timestamp: '10:18 AM',
    tagIds: [],
    poll: {
      id: 'poll-1',
      question: 'When should we freeze code for the final Q3 release candidate?',
      options: [
        { id: 'opt-1', text: 'Thursday 5:00 PM (QA gets full Friday)', voterIds: ['user-bob'] },
        { id: 'opt-2', text: 'Friday 12:00 PM (Extra morning for final polish)', voterIds: ['user-alice', 'user-me'] },
        { id: 'opt-3', text: 'Monday 9:00 AM (Allows weekend staging test)', voterIds: [] },
      ],
      allowMultiple: false,
      createdBy: 'Bob Smith',
      createdAt: '10:18 AM',
    },
  },
  {
    id: 'm5',
    threadId: 't1',
    content: 'Here is the direct link to Bob\'s contrast feedback: [Re: Bob Smith: "The CTA button..."](?threadId=t1&messageId=m3).\nAlso note the executive compensation memo at [Executive Bonus Memo](?threadId=t3&messageId=m-sec-1).',
    sender: 'other',
    senderName: 'Alice Johnson',
    timestamp: '10:20 AM',
    tagIds: [],
  },
  {
    id: 'm6',
    threadId: 't1',
    content: 'Thanks for voting everyone! cc @You and @Bob Smith please review the checklist before noon.',
    sender: 'other',
    senderName: 'Alice Johnson',
    timestamp: '10:25 AM',
    tagIds: [],
  },
  {
    id: 'm-inspire-1',
    threadId: 't1',
    content: '💡 Inspiring interaction benchmark: Check out the Linear keyboard shortcut command menu at https://linear.app/features — the instant tactile feedback and sound cue is brilliant. We should mirror this responsiveness for our tagging palette!',
    sender: 'other',
    senderName: 'Alice Johnson',
    timestamp: '10:28 AM',
    tagIds: ['tg-inspire', 'tg-link'],
  },
  {
    id: 'm-link-1',
    threadId: 't1',
    content: '🔗 Here is the benchmark Figma spec for our dark-mode contrast palette and mathematical radii tokens: https://figma.com/@design/tokens-v3 — all tokens pass WCAG AA standards.',
    sender: 'me',
    senderName: 'You',
    timestamp: '10:32 AM',
    tagIds: ['tg-link'],
  },
  {
    id: 'm-idea-1',
    threadId: 't1',
    content: '🎨 Creative pitch for the project ledger: What if tagged messages auto-compile into an executive digest? Anyone joining the thread can immediately scan Inspiration, Decisions, and Links without wading through 500 messages!',
    sender: 'other',
    senderName: 'Bob Smith',
    timestamp: '10:35 AM',
    tagIds: ['tg-idea'],
  },
  {
    id: 'm-act-1',
    threadId: 't1',
    content: '⚡ Action item: @You finalize the token export script by Thursday 3:00 PM before staging verification.',
    sender: 'other',
    senderName: 'Alice Johnson',
    timestamp: '10:38 AM',
    tagIds: ['tg-action'],
  },
  {
    id: 'm-sec-1',
    threadId: 't3',
    content: 'FY27 Executive bonus allocations and leadership equity distribution draft attached for review.',
    sender: 'other',
    senderName: 'Carol Danvers',
    timestamp: 'Yesterday at 4:30 PM',
    tagIds: ['tg-sec1'],
  },
  {
    id: 'm-sec-2',
    threadId: 't3',
    content: 'Reviewed and confirmed. Keeping this discussion strictly confidential to board members.',
    sender: 'other',
    senderName: 'Bob Smith',
    timestamp: 'Yesterday at 4:45 PM',
    tagIds: [],
  },
  {
    id: 'm-priv-1',
    threadId: 't4',
    content: 'Hi Carol, here is the confidential hiring compensation package for the VP candidate.',
    sender: 'other',
    senderName: 'Bob Smith',
    timestamp: '8:45 AM',
    tagIds: [],
  },
];

export const PRESET_COLORS = [
  'bg-blue-100 dark:bg-blue-950/70 text-blue-700 dark:text-blue-300 border-blue-200 dark:border-blue-800/80',
  'bg-emerald-100 dark:bg-emerald-950/70 text-emerald-700 dark:text-emerald-300 border-emerald-200 dark:border-emerald-800/80',
  'bg-rose-100 dark:bg-rose-950/70 text-rose-700 dark:text-rose-300 border-rose-200 dark:border-rose-800/80',
  'bg-amber-100 dark:bg-amber-950/70 text-amber-700 dark:text-amber-300 border-amber-200 dark:border-amber-800/80',
  'bg-purple-100 dark:bg-purple-950/70 text-purple-700 dark:text-purple-300 border-purple-200 dark:border-purple-800/80',
  'bg-pink-100 dark:bg-pink-950/70 text-pink-700 dark:text-pink-300 border-pink-200 dark:border-pink-800/80',
  'bg-indigo-100 dark:bg-indigo-950/70 text-indigo-700 dark:text-indigo-300 border-indigo-200 dark:border-indigo-800/80',
  'bg-slate-100 dark:bg-slate-800 text-slate-700 dark:text-slate-300 border-slate-200 dark:border-slate-700',
];
